application: gdg-israel
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: web/index.html
  upload: web/index.html
  expiration: "1m"

- url: /
  static_dir: web

libraries:
- name: webapp2
  version: "2.5.2"
